
services:
  backend:
    image: ${REGISTRY_URL:-localhost:5000}/${APP_NAME:-absent}-backend:latest
    build:
      context: ./src/backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: "${BACKEND_PORT:-3000}"
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    restart: unless-stopped

  frontend:
    image: ${REGISTRY_URL:-localhost:5000}/${APP_NAME:-absent}-frontend:latest
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
    restart: unless-stopped