
services:
  mongo:
    image: ${REGISTRY_URL:-localhost:5000}/${APP_NAME:-absent}-mongo:latest
    build:
      context: ./src/database
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME:-absent}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD:-absent}"
      MONGO_INITDB_DATABASE: "${MONGO_DB:-absent}"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    image: ${REGISTRY_URL:-localhost:5000}/${APP_NAME:-absent}-backend:latest
    build:
      context: ./src/backend
      dockerfile: Dockerfile.prod
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    image: ${REGISTRY_URL:-localhost:5000}/${APP_NAME:-absent}-frontend:latest
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
      - mongo
    restart: unless-stopped

volumes:
  mongo-data: